### ISSUE TITLE
关于图片组件方法形参path的类型声明问题

### ISSUE THREAD

**Issue by Hz6826** [Ianzb/program#1]
在widgets.py文件中
```
class Image(QLabel):
    @__init__.register
    def _(self, path: str = None, url: str = None, parent: QWidget = None):
        """
        @param path: 路径
        @param url: 链接
        """
        self.__init__(parent)
        if path:
            self.setImg(path, url)
```
报错
```
Traceback (most recent call last):
  File "D:\Users\Admin\PycharmProjects\program\Windows\main.pyw", line 1, in <module>
    from window import *
  File "D:\Users\Admin\PycharmProjects\program\Windows\window.py", line 3, in <module>
    from widgets import *
  File "D:\Users\Admin\PycharmProjects\program\Windows\widgets.py", line 132, in <module>
    class Image(QLabel):
  File "D:\Users\Admin\PycharmProjects\program\Windows\widgets.py", line 145, in Image
    def _(self, path: str = None, url: str = None, parent: QWidget = None):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\functools.py", line 921, in register
    return self.dispatcher.register(cls, func=method)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\functools.py", line 873, in register
    raise TypeError(
TypeError: Invalid annotation for 'path'. typing.Optional[str] is not a class.
```

而将path: str = None改为path: str后，程序正常工作。

**Comment by Ianzb** [comment]
修复了
